### ISSUE TITLE
Fix data appears to be broken after recent changes

### ISSUE THREAD

**Issue by pwoo** [adriangibbons/php-fit-file-analysis#10]
Which may be related to how records are being parsed internally. The error being output is:

```
  [ErrorException]            
  Undefined index: timestamp  
```

I can provide FIT files on request.

**Comment by adriangibbons** [comment]
Hi @pwoo, I've just taken a look and fixed the error.

I had accidentally removed `$this->data_mesgs['record']['timestamp']`, but I've added it back it now. I also made a small enhancement to the `fix_data()` function.

When I get round to creating some PHPUnit tests (#9), I should prevent these things from happening!

Please let me know if the error persists and we can re-open this issue.

Thanks, Adrian.

**Comment by adriangibbons** [comment]
When I get round to
