### ISSUE TITLE
develop getJSON() function

### ISSUE THREAD

**Issue by adriangibbons** [adriangibbons/php-fit-file-analysis#28]
Would be useful to get data in a JSON format e.g. for use in dc.js

``` JSON
{
    "fix_data": "all",
    "units": "metric",
    "pace": null,
    "data": [
        {
            "timestamp": 71234828,
            "lap": 1,
            "pos_latitude": 32.15,
            "pos_longitude": 115.24,
            "speed": 29.3,
            "altitude": 15,
            "cadence": 91,
            "heart_rate": 116,
            "power": 189,
            "chainring": 53,
            "sprocket": 19
        },
        {
            "timestamp": 71234832,
            "lap": 1,
            "pos_latitude": 32.16,
            "pos_longitude": 115.23,
            "speed": 28.1,
            "altitude": 15,
            "cadence": null,
            "heart_rate": 121,
            "power": 0,
            "chainring": 53,
            "sprocket": 18
        }
    ]
}
```

Could create the array structure in PHP and then use:

``` php
<?php json_encode(); ?>
```

**Comment by adriangibbons** [comment]
It's beginning!...

![image](https://cloud.githubusercontent.com/assets/10218647/9818815/f5095d8c-58dc-11e5-8989-433b579b21df.png)

**Comment by gfrogley** [comment]
That's really cool Adrian!
I've been looking at the dc.js site you mentioned too and had several thoughts. Can you get all the data out in json format? If so, then graphing the sets would be (ahem) straight forward. Seemingly all graphs can react to a filtered dataset. If one graph was changed then the others, quadrant analysis and map would follow suit. This would enable finer selection... A coach could select repeats of a hill and see the cadence, force and compare with subsequent ascents. HR and power pie charts would also be interesting to look at. I'll try to find some time this weekend to take a closer look at the code, but I need to get out on my bike for a change! I think this ability might even go beyond what training peaks premium can offer.
Cheers
Graham

**Comment by adriangibbons** [comment]
Thanks @gfrogley

So I haven't got it all working, laps with the map in particular are a bit off, but I thought I'd upload anyway: http://adriangibbons.com/php-fit-file-analysis/demo/quadrant-analysis.php

https://github.com/adriangibbons/php-fit-file-analysis/commit/d4cf743a6d49a68237989db31cb8e75f6a4a1f01 has included quadrant-analysis.php (and required files) in the demo folder. If you use a different FIT file with laps, you'll be able to filter the data based on laps. You can also click and drag on the two histograms!

Keen to here your thoughts and how we can make this better!

Enjoy the riding! I'm doing a 140km ride known as the Hell of the North in Western Australia because it's usually very windy :S

**Comment by gfrogley** [comment]
Check out cyclcoaching.ddns.net/dc.php

The map seems to go a bit screwy when segment data is selected. It looks
like the co-ords are rearranged during the import, but I might be wrong. If
you zoom in enough you can see blue criss-cross lines. It seems to get
muddled when latlngDim gets index again when a lap is selcted, but I cant
suggest a resolution, its way out of my experience!
Graham

**Comment by gfrogley** [comment]
try _cyclecoaching_ instead.... crap keyboard!

**Comment by gfrogley** [comment]
been thinking, this question may help
http://stackoverflow.com/questions/30868801/crossfiltering-of-json-data-by-the-most-recent-time
but I have absolutely no idea on how to implement it.

**Comment by adriangibbons** [comment]
Hey, no dramas. I am back from my 140km ride and a bit achey, but I managed to fix the issue. Basically, the issue lay with the fact that the lat/lng dimension (latlngDim) was being sorted by crossfilter.js - as it should:

> **[# dimension.top(k)](https://github.com/square/crossfilter/wiki/API-Reference#dimension_top)**
> Returns a new array containing the top k records, according to the natural order of this dimension. _The returned array is sorted by descending natural order_.

So instead, I pass a timestamp dimension to the `updateOverlay()` function. Now it works just fine as the timestamps are sorted instead of the lat/lng's.

**CRAP** just realised that as I'm using `dimension.top(k)`, the timestamps are the wrong way round as they are sorted in descending order. I will switch to `dimension.bottom(k)` straight after I post this! The result looks the same, but I guess I should make it the right way round!

Thanks for pointing out the lines were crisscrossing as that helped me figure that the lat/long array had been sorted! I initially thought a fill was being applied to the lines when they intersected themselves.

**Comment by adriangibbons** [comment]
Need to add input to request which values should be returned in the JSON:

> timestamp (always include?)
> paused
> temperature
> lap (always include?)
> pos_latitude
> pos_longitude
> distance
> altitude
> speed
> heart_rate
> cadence
> power
> chainring
> sprocket

**Comment by adriangibbons** [comment]
Closed by https://github.com/adriangibbons/php-fit-file-analysis/commit/36f398e7a4d91cbb520a3d34a154761304644d0b
