### ISSUE TITLE
Add ATL, CTL and TSB to Power Analysis

### ISSUE THREAD

**Issue by adriangibbons** [adriangibbons/php-fit-file-analysis#31]
New public function to take TSS's as input and return:
- Acute Training Load (Fatigue)
- Chronic Training Load (Fitness)
- Training Stress Balance (Form)

E.g. `getFatigueFitnessForm($tss_values, $ctl_time_period = 84days, $atl_time_period = 14days)`

**Comment by adriangibbons** [comment]
TSS already included in ```powerMetrics()``` !!!

**Comment by ehsan-soleimanian** [comment]
Hello Adrian
this functions needs previous athlete's data for calculating while your library's functions  often works on one activity only.
I'd like to contribute .May I have your contact info?
