### ISSUE TITLE
example for leaflet js

### ISSUE THREAD

**Issue by pitcock** [adriangibbons/php-fit-file-analysis#62]
Hi,

is there also a "mountain-biking.php" example using the OpenStreetMap services with leaflet.js instead of Google maps?

Regards

**Comment by adriangibbons** [comment]
Hi, I have used it with both Leaflet and GMaps - found switching between the two fairly straightforward. I had a quick look but couldn't find an example I could quickly share but will have another look later.

**Comment by adriangibbons** [comment]
Hey, I just knocked a quick example together and committed to the demo folder in 3a445ff

Note the code is quite old now - the examples still use Bootstrap 3

**Comment by pitcock** [comment]
Thanks a lot
